from .comparator import Comparator
from .image_comparator import ImageComparator
from .color_comparator import ColorComparator
from .average_color_comparator import AverageColorComparator
from .dominant_color_comparator import DominantColorComparator
from .file_name_comparator import FileNameComparator
